author/views.py
from flask import Blueprint, render_template, redirect, session, request, url_for, flash
from werkzeug.security import generate_password_hash

from application import db
from author.models import Author
from author.forms import RegisterForm, LoginForm

author_app = Blueprint('author_app', __name__)

@author_app.route('/register', methods=('GET', 'POST'))
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)
        author = Author(
            form.full_name.data,
            form.email.data,
            hashed_password
        )
        db.session.add(author)
        db.session.commit()
        flash("You are now registered, please login")
        return redirect(url_for('.login'))
    return render_template('author/register.html', form=form)

@author_app.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    error = None

    if request.method == 'GET' and request.args.get('next'):
        session['next'] = request.args.get('next', None)

    if form.validate_on_submit():
        author = Author.query.filter_by(email=form.email.data).first()
        session['id'] = author.id
        session['full_name'] = author.full_name
        if 'next' in session:
            next = session.get('next')
            session.pop('next')
            return redirect(next)
        else:
            return redirect(url_for('blog_app.index'))

    return render_template('author/login.html', form=form, error=error)

@author_app.route('/logout')
def logout():
    session.pop('id')
    session.pop('full_name')
    flash("User logged out")
    return redirect(url_for('.login'))

blog/views.py
from flask import Blueprint, render_template, session, flash, redirect, url_for, request, abort
from slugify import slugify
import uuid
import os
from PIL import Image

from application import db
from blog.models import Post, Category, Tag, Goverment
from blog.forms import PostForm
from author.models import Author
from author.decorators import login_required
from settings import BLOG_POST_IMAGES_PATH


blog_app = Blueprint('blog_app', __name__)

POSTS_PER_PAGE = 5

@blog_app.route('/')
def index():
    page = int(request.values.get('page', '1'))
    posts = Post.query.filter_by(live=True).order_by(Post.publish_date.desc())\
        .paginate(page, POSTS_PER_PAGE, False)
    cats=Category.query.order_by(Category.name).all()
    return render_template('blog/index.html',
        posts=posts,
        cats=cats,
        title='Index'
    )

@blog_app.route('/post', methods=('GET', 'POST'))
@login_required
def post():
    form = PostForm()
    tags_field = request.values.get('tags_field', '')

    if form.validate_on_submit():
        image_id = None

        if form.image.data:
            f = form.image.data
            image_id = str(uuid.uuid4())
            file_name = image_id + '.png'
            file_path = os.path.join(
                BLOG_POST_IMAGES_PATH, file_name
            )
            Image.open(f).save(file_path)

            _image_resize(BLOG_POST_IMAGES_PATH, image_id, 600, 'lg')
            _image_resize(BLOG_POST_IMAGES_PATH, image_id, 300, 'sm')

        if form.new_category.data:
            new_category = Category(form.new_category.data)
            db.session.add(new_category)
            db.session.flush()
            category = new_category
        else:
            category = form.category.data

        
        if form.new_goverment.data:
            new_goverment = Goverment(form.new_goverment.data)
            db.session.add(new_goverment)
            db.session.flush()
            goverment = new_goverment
        else:
            goverment = form.goverment.data

        author = Author.query.get(session['id'])
        title = form.title.data.strip()
        body = form.body.data.strip()
        post = Post(
            author=author,
            title=title,
            body=body,
            image=image_id,
            category=category,
            goverment=goverment,
        )

        _save_tags(post, tags_field)

        db.session.add(post)
        db.session.commit()

        slug = slugify(str(post.id) + '-' + post.title)
        post.slug = slug
        db.session.commit()  

        flash('Article posted')
        return redirect(url_for('.article', slug=slug))      

    return render_template('blog/post.html',
        form=form,
        action="new",
        tags_field=tags_field   
    )

@blog_app.route('/posts/<slug>')
def article(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    return render_template('blog/article.html', post=post)

@blog_app.route('/edit/<slug>', methods=('GET', 'POST'))
@login_required
def edit(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    form = PostForm(obj=post)
    tags_field = request.values.get('tags_field', _load_tags_field(post))

    if form.validate_on_submit():
        original_image = post.image
        original_title = post.title
        form.populate_obj(post)

        if form.image.data:
            f = form.image.data
            image_id = str(uuid.uuid4())
            file_name = image_id + '.png'
            file_path = os.path.join(
                BLOG_POST_IMAGES_PATH, file_name
            )
            Image.open(f).save(file_path)

            _image_resize(BLOG_POST_IMAGES_PATH, image_id, 600, 'lg')
            _image_resize(BLOG_POST_IMAGES_PATH, image_id, 300, 'sm')

            post.image = image_id
        else:
            post.image = original_image
        
        if form.new_category.data:
            new_category = Category(form.new_category.data)
            db.session.add(new_category)
            db.session.flush()
            post.category = new_category

        #if form.new_goverment.data:
        #    new_goverment = Goverment(form.new_goverment.data)
        #    db.session.add(new_goverment)
        #    db.session.flash()
            post.goverment = new_goverment

        if form.title.data != original_title:
            post.slug = slugify(str(post.id) + '-' + form.title.data)

        _save_tags(post, tags_field)

        db.session.commit()
        flash('Article edited')
        return redirect(url_for('.article', slug=post.slug))

    return render_template('blog/post.html',
        form=form,
        post=post,
        action="edit",
        tags_field=tags_field
    )

@blog_app.route('/delete/<slug>')
@login_required
def delete(slug):
    post = Post.query.filter_by(slug=slug).first_or_404()
    post.live = False
    db.session.commit()
    flash("Article deleted")
    return redirect(url_for('.index'))

@blog_app.route('/categories/<category_id>')
@blog_app.route('/categories/')
def categories(category_id=None):
    page = int(request.values.get('page', '1'))
    cats=Category.query.order_by(Category.name).all()
    
    if category_id is None:
        category = ''
        posts = Post.query.filter_by(live=True).order_by(Post.publish_date.desc())\
        .paginate(page, POSTS_PER_PAGE, False)
    else :
        category = Category.query.filter_by(id=category_id).first_or_404()  
        posts = Post.query.filter_by(category=category, live=True)\
            .order_by(Post.publish_date.desc())\
            .paginate(page, POSTS_PER_PAGE, False)
    
    return render_template('blog/category_posts.html',
        posts=posts,
        cats=cats,
        category=category,
        category_id=category_id
    )

@blog_app.route('/tags/<tag>')
def tags(tag):
    tag = Tag.query.filter_by(name=tag).first_or_404()
    page = int(request.values.get('page', '1'))
    posts = tag.posts.filter_by(live=True)\
        .order_by(Post.publish_date.desc())\
        .paginate(page, POSTS_PER_PAGE, False)
    return render_template('blog/tag_posts.html',
        posts=posts,
        title="Tag: " + str(tag),
        tag=str(tag)
    )    

def _image_resize(original_file_path,image_id, image_base, extension):
    file_path = os.path.join(
        original_file_path, image_id + '.png'
    )
    image = Image.open(file_path)
    wpercent = (image_base / float(image.size[0]))
    hsize = int((float(image.size[1]) * float(wpercent)))
    image = image.resize((image_base, hsize), Image.ANTIALIAS)
    modified_file_path = os.path.join(
        original_file_path, image_id + '.' + extension + '.png'
    )
    image.save(modified_file_path)
    return

def _save_tags(post, tags_field):
    post.tags.clear()
    for tag_item in tags_field.split(','):
        tag = Tag.query.filter_by(name=slugify(tag_item)).first()
        if not tag:
            tag = Tag(name=slugify(tag_item))
            db.session.add(tag)
        post.tags.append(tag)
    return post

def _load_tags_field(post):
    tags_field = ''
    for tag in post.tags:
        tags_field += tag.name + ', '
    return tags_field[:-2]

@blog_app.route('/details/<detail_id>')
def details(detail_id):
    if int(detail_id) > 3:
        abort(404)
    return render_template('blog/carousel_details.html', detail_id=detail_id)

templates/_flashmessages.html
{% with messages = get_flashed_messages() %}
{% if messages %}
<div id="messages">
  {% for message in messages %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
</button>
  </div>
  {% endfor %}
</div>
{% endif %}
{% endwith %}

templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
  {{ field.label }}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class="text-danger">
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
</div>
{% endmacro %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>

    <!-- bootstrap -->
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" >
        <link rel="stylesheet" href="../static/css/bootstrap.min.css")>
        
    -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" >
  </head>
  <body>
  <main role="main">
    {% block nav %}{% endblock %}
    
    <div class="container-fluid">
    {% block carousel%}{% endblock %}

    {% block content %}{% endblock %}

      <div class="container-fluid bg-secondary pt-5 pb-3">
        <footer >
        <div class="col-md-12">
          <p class="text-center" ><span class="text-white">สงวนลิขสิทธิ์ พ.ศ. 2562 ตามพระราชบัญญัติลิขสิทธิ์ 2537 สำนักงานพัฒนารัฐบาลดิจิทัล (องค์การมหาชน) (สพร.)</br>
             โทรศัพท์ : (+66) 0 2612 6000 โทรสาร : (+66) 0 2612 6011-12 อีเมล : contact@dga.or.th </span></p>
        </div>
        </footer>
      </div>

    </div>
  </main>
    <!-- bootstrap
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/jquery-3.4.1.slim.min.js') }}"></script>
  --> 
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
  </body>
</html>

templates/carousel.html
{% if session.id %}
    <div class="pb-3"></div>
{% else %} 
    <div id="myCarousel" class="carousel slide pb-3 " data-ride="carousel">
        <ol class="carousel-indicators ">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <svg class="bd-placeholder-img" width="100%" height="300" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg>
            <div class="container" >
              <div class="carousel-caption text-left">
                <h1>Reference Data</h1>
                <h6>คือ ชุดข้อมูลมาตรฐานที่ใช้งานร่วมกันหรือรายการค่าข้อมูลที่สามารถใช้งานร่วมกันได้</h6></br>
                <p><a class="btn btn-lg btn-primary" href="{{ url_for('.details', detail_id=1)}}" role="button">รายละเอียด</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <svg class="bd-placeholder-img" width="100%" height="300" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg>
            <div class="container">
              <div class="carousel-caption">
                <h1>Another example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="{{ url_for('.details', detail_id=2)}}" role="button">รายละเอียด</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <svg class="bd-placeholder-img" width="100%" height="300" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg>
            <div class="container">
              <div class="carousel-caption text-right">
                <h1>มาตรฐานการจัดทำข้อมูลอ้างอิง</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="{{ url_for('.details', detail_id=3)}}" role="button">รายละเอียด</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
{% endif %}

templates/catalog.html
<div class="container text-center">
        <!-- Three columns of text below the carousel -->
      <div class="row">
      {% for cat in cats %}      
        {% if cat %} 
         <div class="col">
            <svg class="bd-placeholder-img rounded-circle"  width="100" height="100" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
            <p></p>
            <p><a class="btn btn-primary" href="{{ url_for('.categories', category_id=cat.id)}}" role="button">{{ cat.name }} &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
        {% endif %}
      {% endfor %}
    </div><!-- /.row -->
</div><!-- /.container -->    

templates/nav.html
<div class="container-fluid" >
  <nav class="navbar navbar-expand-lg  navbar-light bg-light">
      <a class="navbar-brand" href="{{ url_for('blog_app.index') }}">{{ config['BLOG_NAME'] }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarsExample01"  >
      <ul class="navbar-nav ml-auto" >
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('blog_app.categories')}}">หมวดหมู่</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">เกี่ยวกับ</a>
        </li>
        &nbsp;
        &nbsp;
        {% if session.id %}
          <li class="nav-item">
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ session.full_name }}</a>
                  <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="{{ url_for('blog_app.post')}}"> New Post</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
              </li>
          </li>
            &nbsp;
          <li>
          </li>
          <li class="nav-item">
            <a class="btn btn-outline-primary" href="{{ url_for('author_app.logout')}}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="btn btn-outline-primary" href="{{ url_for('author_app.login')}}">Login</a>
          </li>
        {% endif %}
       </ul>
    </div>
  </nav>

</div>